
######## USUARIO INICIO ############

prueba_usuarios:
  path: /usuario 
  defaults: { _controller: PruebaBundle:Default:usuario}

prueba_postUser:
  path: /usuario/post 
  defaults: { _controller: PruebaBundle:Default:postUser}
  methods:  [GET,POST]

# USUARIO FIN



######### INICIO AREA ###########

prueba_getArea:
  path: /area/get 
  defaults: { _controller: PruebaBundle:Area:getArea }
  methods:  [GET,POST]

# FIN AREA 


######### INICIO RESPONSABLE ACUERDO ###########

prueba_getResponsableAcuerdo:
  path: /responsable/post 
  defaults: { _controller: PruebaBundle:Area:postArea }
  methods:  [GET,POST]

prueba_responsableAcuerdo:
  path: /responsable-acuerdo 
  defaults: { _controller: PruebaBundle:Area:responsableAcuerdo}
  methods:  [GET,POST]

prueba_responsableAcuerdoNuevo:
  path: /responsable-acuerdo/nuevo 
  defaults: { _controller: PruebaBundle:Area:responsableAcuerdoNuevo}
  methods:  [GET,POST]

prueba_responsableAcuerdoEditar:
  path: /responsable-acuerdo/editar/{id} 
  defaults: { _controller: PruebaBundle:Area:responsableAcuerdoUpdate}
  methods:  [GET,POST]

prueba_responsableAcuerdoRemove:
  path: /responsable-acuerdo/remove/{id} 
  defaults: { _controller: PruebaBundle:Area:responsableAcuerdoRemove}
  methods:  [GET,POST]

# FIN RESPONSABLE ACUERDO 


########## LOGIN AND LOGOUT INICIO ##########

prueba_login:
  path: /login 
  defaults: { _controller: PruebaBundle:Default:login}

prueba_logout:
  path: /logout

#LOGIN AND LOGOUT FIN



########## INICIO PRINCIPAL #########


prueba_principal:
  path: /
  defaults: { _controller: PruebaBundle:Default:principal }


#FIN PRINCIPAL



########### ACUERDOS PRE ##########

prueba_acuerdosPre:
  path: /acuerdosPre 
  defaults: { _controller: PruebaBundle:AcuerdosPre:acuerdosPre}
  methods:  [GET,POST]

prueba_postAcuerdosPre:
  path: /acuerdosPre/post 
  defaults: { _controller: PruebaBundle:AcuerdosPre:acuerdosPrePost}
  methods:  [GET,POST]

prueba_getAcuerdosPre:
  path: /acuerdosPre/get 
  defaults: { _controller: PruebaBundle:AcuerdosPre:acuerdosPreGet}
  methods:  [GET,POST]

prueba_acuerdosPreUpdate:
  path: /acuerdosPre/update/{id} 
  defaults: { _controller: PruebaBundle:AcuerdosPre:acuerdosPreUpdate}
  methods:  [GET,POST]

prueba_nuevoAcuerdosPre:
  path: /acuerdosPre/nuevo 
  defaults: { _controller: PruebaBundle:AcuerdosPre:acuerdosPreNuevo}
  methods:  [GET,POST]

prueba_acuerdosPreRemove:
  path: /acuerdosPre/remove/{id}
  defaults: { _controller: PruebaBundle:AcuerdosPre:acuerdosPreRemove}
  methods:  [GET,POST]

#FIN ACUERDOS PRE

########### ACUERDOS SG ##########

prueba_acuerdosSG:
  path: /acuerdosSG 
  defaults: { _controller: PruebaBundle:AcuerdosSG:acuerdosSG}
  methods:  [GET,POST]


prueba_acuerdosSGUpdate:
  path: /acuerdosSG/update/{id} 
  defaults: { _controller: PruebaBundle:AcuerdosSG:acuerdosSGUpdate}
  methods:  [GET,POST]

prueba_acuerdosSGRemove:
  path: /acuerdosSG/remove/{id}
  defaults: { _controller: PruebaBundle:AcuerdosSG:acuerdosSGRemove}
  methods:  [GET,POST]  

prueba_nuevoAcuerdosSG:
  path: /acuerdosSG/nuevo 
  defaults: { _controller: PruebaBundle:AcuerdosSG:acuerdosSGNuevo}
  methods:  [GET,POST]

prueba_getAcuerdosSG:
  path: /acuerdosSG/get 
  defaults: { _controller: PruebaBundle:AcuerdosSG:acuerdosSGGet}
  methods:  [GET,POST]

#FIN ACUERDOS SG


############## OBSERVACIONES PRE ##############

prueba_observacionesPrePost:
  path: /observacionesPre/post 
  defaults: { _controller: PruebaBundle:ObservacionesPre:observacionesPrePost}
  methods:  [GET,POST]


prueba_email:
  path: /email 
  defaults: { _controller: PruebaBundle:DetalleIndicador:email}
  
#FIN OBSERVACIONES PRE

############## INDICADOR ##############

prueba_getIndicador:
  path: /indicador/get
  defaults: { _controller: PruebaBundle:Indicador:getIndicador }


#FIN

############## OBSERVACIONES SG ##############

prueba_observacionesSGPost:
  path: /observacionesSG/post 
  defaults: { _controller: PruebaBundle:ObservacionesSG:observacionesSGPost}
  methods:  [GET,POST]


#FIN OBSERVACIONES SG


prueba_formIndicador:
  path: /indicador
  defaults: { _controller: PruebaBundle:Indicador:formIndicador }

#INICIO LEYENDA

prueba_postLeyenda:
  path: /disede/leyenda/post
  defaults: { _controller: PruebaBundle:Leyenda:postLeyenda }  
  methods:  [GET,POST]

prueba_getLeyenda:
  path: /disede/leyenda/get
  defaults: { _controller: PruebaBundle:Leyenda:getLeyenda }  
  methods:  [GET,POST]

prueba_leyenda:
  path: /disede/leyenda
  defaults: { _controller: PruebaBundle:Leyenda:leyenda }
  methods:  [GET,POST]

#FIN LEYENDA


#INICIO DETALLE_INDICADOR

prueba_nuevoDetalleIndicadorPrueba:
  path: /prueba
  defaults: { _controller: PruebaBundle:DetalleIndicador:prueba }

prueba_nuevoDetalleIndicador:
  path: /nuevo-detalle-indicador/{tipo}
  defaults: { _controller: PruebaBundle:DetalleIndicador:nuevoDetalleIndicador }

prueba_updateDetalleIndicador:
  path: /disede/detalleindicador/update/{id}
  defaults: { _controller: PruebaBundle:DetalleIndicador:updateDetalleIndicador }

prueba_verDetalleIndicador:
  path: /disede
  defaults: { _controller: PruebaBundle:DetalleIndicador:verDetalleIndicador }

prueba_postTotal:
  path: /total/post
  defaults: { _controller: PruebaBundle:DetalleIndicador:postTotal }
  methods:  [GET,POST]

prueba_getTotalIndicadores:
  path: /detalleindicador/total-indicadores/get
  defaults: { _controller: PruebaBundle:DetalleIndicador:postTotalSave }
  methods:  [GET,POST]


prueba_postIdGraficos:
  path: /graficos/id/post
  defaults: { _controller: PruebaBundle:Indicador:postIdDetalleIndicador}
  methods:  [GET,POST]

prueba_detalleIndicadorGrafica:
  path: /detalleindicador/graficos/{id}
  defaults: { _controller: PruebaBundle:DetalleIndicador:detalleIndicadorGrafica }
  methods:  [GET,POST]

prueba_detalleIndicadorGraficaForm:
  path: /detalleindicador/graficos/form/{id}
  defaults: { _controller: PruebaBundle:DetalleIndicador:detalleIndicadorGraficaForm }
  methods:  [GET,POST]

#FIN 

#INICIO TOTAL INDICADOR

prueba_postTotalInicio:
  path: /total
  defaults: { _controller: PruebaBundle:DetalleIndicador:postTotalInicio }
  methods:  [GET,POST]

#FIN



prueba_postajax:
  path: /ajax/posts
  defaults: { _controller: PruebaBundle:DetalleIndicador:posts }
  methods:  [GET,POST]

prueba_mostrar:
  path: /mostrar
  defaults: { _controller: PruebaBundle:Post:mostrarPost } 

#PRUEBA INGRESO DE USUARIO

prueba_register:
  path: /register
  defaults: { _controller: PruebaBundle:Default:register }


#SEND MAIL
prueba_sendMail:
  path: /sendmail
  defaults: { _controller: PruebaBundle:AcuerdosPre:sendemail }

prueba_sendMailSG:
  path: /sendmail/SG
  defaults: { _controller: PruebaBundle:AcuerdosSG:sendemail }

#FIN SEND MAIL