
######## USUARIO INICIO ############

prueba_usuarios:
  path: /usuario 
  defaults: { _controller: PruebaBundle:Default:usuario}

prueba_postUser:
  path: /usuario/post 
  defaults: { _controller: PruebaBundle:Default:postUser}
  methods:  [GET,POST]

# USUARIO FIN





######### INICIO AREA ###########

prueba_getArea:
  path: /area/get 
  defaults: { _controller: PruebaBundle:Area:getArea }
  methods:  [GET,POST]

# FIN AREA 





########## LOGIN AND LOGOUT INICIO ##########

prueba_login:
  path: /login 
  defaults: { _controller: PruebaBundle:Default:login}

prueba_logout:
  path: /logout

#LOGIN AND LOGOUT FIN



########## INICIO PRINCIPAL #########


prueba_principal:
  path: /
  defaults: { _controller: PruebaBundle:Default:principal }


#FIN PRINCIPAL




prueba_formIndicador:
  path: /indicador
  defaults: { _controller: PruebaBundle:Indicador:formIndicador }


prueba_indicadorajaxIndicador:
  path: /ajax/indicador
  defaults: { _controller: PruebaBundle:Indicador:indicadorajax }

prueba_postTotalIndicadorAjax:
  path: /ajax/totalindicador
  defaults: { _controller: PruebaBundle:DetalleIndicador:postTotalIndicadorAjax }
  methods:  [GET,POST]



#INICIO LEYENDA

prueba_postLeyenda:
  path: /disede/leyenda/post
  defaults: { _controller: PruebaBundle:Leyenda:postLeyenda }  
  methods:  [GET,POST]

prueba_getLeyenda:
  path: /disede/leyenda/get
  defaults: { _controller: PruebaBundle:Leyenda:getLeyenda }  
  methods:  [GET,POST]

prueba_leyenda:
  path: /disede/leyenda
  defaults: { _controller: PruebaBundle:Leyenda:leyenda }
  methods:  [GET,POST]

#FIN LEYENDA


#INICIO DETALLE_INDICADOR

prueba_formDetalleIndicador:
  path: /formdetalleindicador
  defaults: { _controller: PruebaBundle:DetalleIndicador:formDetalleIndicador }

prueba_updateDetalleIndicador:
  path: /updatedetalleindicador/{id}
  defaults: { _controller: PruebaBundle:DetalleIndicador:updateDetalleIndicador }

prueba_verDetalleIndicador:
  path: /disede
  defaults: { _controller: PruebaBundle:DetalleIndicador:verDetalleIndicador }

prueba_postTotalAjax:
  path: /detalleindicador/ajax/post
  defaults: { _controller: PruebaBundle:DetalleIndicador:postTotalAjax }
  methods:  [GET,POST]



prueba_postTotalSave:
  path: /detalleindicador/total/post
  defaults: { _controller: PruebaBundle:DetalleIndicador:postTotalSave }
  methods:  [GET,POST]


prueba_postIdGraficos:
  path: /graficos/id/post
  defaults: { _controller: PruebaBundle:Indicador:postIdDetalleIndicador}
  methods:  [GET,POST]

#FIN DETALLE_INDICADOR



prueba_detalleIndicadorGrafica:
  path: /detalleindicador/graficos/{id}
  defaults: { _controller: PruebaBundle:DetalleIndicador:detalleIndicadorGrafica }
  methods:  [GET,POST]

prueba_postajax:
  path: /ajax/posts
  defaults: { _controller: PruebaBundle:DetalleIndicador:posts }
  methods:  [GET,POST]

prueba_mostrar:
  path: /mostrar
  defaults: { _controller: PruebaBundle:Post:mostrarPost } 

