# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    

    providers:
        in_memory:
                memory:
                    users:
                        ryan:
                            password: ryanpass
                            roles: 'ROLE_USER'
                        admin:
                            password: 1234
                            roles: 'ROLE_ADMIN'

        our_db_provider:
            entity:
                class: PruebaBundle:Usuario
                property: username
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        #PruebaBundle\Entity\Usuario: bcrypt
        PruebaBundle\Entity\Usuario: plaintext
        
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin: 

            pattern: ^/admin
            http_basic: ~

        prueba:
            anonymous: ~
            pattern: ^/   
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login 
            http_basic: ~
            logout:
                path: /logout
                target: /login

        main:
            anonymous: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, roles: [ROLE_USER , ROLE_ADMIN] }
    
    