<?php

namespace PruebaBundle\Repository;

/**
 * AcuerdosPreAreaIpdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcuerdosPreAreaIpdRepository extends \Doctrine\ORM\EntityRepository
{
}
