<?php

namespace PruebaBundle\Repository;

/**
 * AcuerdosPreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcuerdosPreRepository extends \Doctrine\ORM\EntityRepository
{
}
