<?php

namespace PruebaBundle\Repository;

/**
 * AcuerdosSGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcuerdosSGRepository extends \Doctrine\ORM\EntityRepository
{


	public function getCantidadEstadoSG($estado){

        $query = "select count(estado) as cantidadEstado from acuerdos_s_g  where estado = '$estado' and  baja='1';";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        $countEstado = $stmt->fetchAll();

        return $countEstado;

	}

	public function getCantidadSG(){

        $query = "select count(estado) as cantidadEstado from acuerdos_s_g where baja='1';";
        $stmt = $this->getEntityManager()->getConnection()->prepare($query);
        $stmt->execute();
        $countSG = $stmt->fetchAll();

        return $countSG;

	}

}
