<?php

namespace PruebaBundle\Repository;

/**
 * AcuerdosSGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcuerdosSGRepository extends \Doctrine\ORM\EntityRepository
{
}
