<?php

namespace PruebaBundle\Repository;

/**
 * AreaIpdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AreaIpdRepository extends \Doctrine\ORM\EntityRepository
{
}
