<?php

namespace PruebaBundle\Repository;

/**
 * DetalleIndicadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleIndicadorRepository extends \Doctrine\ORM\EntityRepository
{
}
