<?php

namespace PruebaBundle\Repository;

/**
 * LeyendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeyendaRepository extends \Doctrine\ORM\EntityRepository
{
}
