<?php

namespace PruebaBundle\Repository;

/**
 * ObservacionesPreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionesPreRepository extends \Doctrine\ORM\EntityRepository
{
}
