<?php

namespace PruebaBundle\Repository;

/**
 * ObservacionesSGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservacionesSGRepository extends \Doctrine\ORM\EntityRepository
{
}
