<?php

namespace PruebaBundle\Repository;

/**
 * ResponsableAcuerdoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableAcuerdoRepository extends \Doctrine\ORM\EntityRepository
{
}
