<?php

namespace PruebaBundle\Repository;

/**
 * ResponsableAcuerdoSGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableAcuerdoSGRepository extends \Doctrine\ORM\EntityRepository
{
}
