<?php

namespace PruebaBundle\Repository;

/**
 * ResponsableAcuerdoPreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsableAcuerdoPreRepository extends \Doctrine\ORM\EntityRepository
{
}
