<?php

namespace PruebaBundle\Repository;

/**
 * TotalIndicadoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TotalIndicadoresRepository extends \Doctrine\ORM\EntityRepository
{
}
